name: "Extract Env Label"
description: "A custom action to update a yaml property and create a PR if updated."

inputs:
  token:
    description: "GitHub token"
    required: true
  pr_number:
    description: "PR number"
    required: true
  repository:
    description: "Repository"
    required: true
outputs:
  env:
    value: ${{ steps.filter-labels.outputs.env }}
    description: "Environment label"
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch labels that a given PR has
      id: fetch-labels
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        chmod +x ./fetch_labels.sh
        output=$(./fetch_labels.sh)
        echo "labels=$output" >> $GITHUB_OUTPUT

    - name: Filter env labels
      id: filter-labels
      shell: bash
      env: 
        LABELS: ${{ steps.fetch-labels.outputs.labels }}
      run: |
        chmod +x ./filter_labels.sh
        output=$(./filter_labels.sh)
        echo "env=$output" >> $GITHUB_OUTPUT
