name: "Extract Env Label"
description: "A custom action to update a yaml property and create a PR if updated."

inputs:
  token:
    description: "GitHub token"
    required: true
  pr_number:
    description: "PR number"
    required: true
  repository:
    description: "Repository"
    required: true
outputs:
  env:
    value: ${{ steps.label.outputs.env }}
    description: "Environment label"
runs:
  using: composite
  steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch labels that a given PR has
      id: label
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        labels_json=$(gh api "repos/xctions/xctions-tests/issues/21/labels")
        echo "labels_json: $labels_json"

        filtered_labels=$(echo "$labels_json" | jq -r '[.[] | select(.name == "dev" or .name == "test" or .name == "stag" or .name == "qa" or .name == "prod") | .name]')
        echo "filtered_labels: $filtered_labels"

        echo "labels=$filtered_labels" >> $GITHUB_OUTPUT

        len=$(echo "$filtered_labels" | jq 'length')
        echo  "len: $len"

        if [ "$len" -ne 1 ]; then
          echo "Error: Expected exactly one environment label, but found $len"
          exit 1
        fi

        env=$(echo "$filtered_labels" | jq -r '.[0]')
        echo "Environment label: $env"
        echo "env=$output" >> $GITHUB_OUTPUT
