name: "Extract Env Label"
description: "A custom action to update a yaml property and create a PR if updated."

inputs:
  token:
    description: "GitHub token"
    required: true
  pr_number:
    description: "PR number"
    required: true
  repository:
    description: "Repository"
    required: true
outputs:
  env:
    value: ${{ steps.filter-labels.outputs.env }}
    description: "Environment label"
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch labels that a given PR has
      id: fetch-labels
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        echo "Fetching labels for PR #${{ inputs.pr_number }} in repository ${{ inputs.repository }}"
        labels=$(gh api "repos/${{ inputs.repository }}/issues/${{ inputs.pr_number }}/labels" --jq '.[].name')
        echo "Raw labels: $labels"
        labels=$(echo "$labels" | jq -r 'map(select(. == "dev" or . == "test" or . == "stag" or . == "qa" or . == "prod"))')
        echo "Filtered labels: $labels"
        echo "labels=$labels" >> $GITHUB_OUTPUT

    - name: Filter env labels
      id: filter-labels
      shell: bash
      env: 
        LABELS: ${{ steps.fetch-labels.outputs.labels }}
      run: |
        echo "Filtering labels: $LABELS"
        len=$(echo "$LABELS" | jq 'length')
        if [ "$len" -ne 1 ]; then
          echo "Error: Expected exactly one environment label, but found $len"
          exit 1
        fi
        env=$(echo "$LABELS" | jq -r '.[0]')
        echo "env=$env" >> $GITHUB_OUTPUT